
import jsPDF from 'jspdf';
import type { SubCategory, Snippet } from '../lib/cheatsheets';

export async function generateCheatsheetPDF(
  categoryName: string,
  subCategory: SubCategory,
  customTitle?: string,
  customSubtitle?: string
) {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = 210;
  const pageHeight = 297;
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;
  const maxY = pageHeight - margin;

  // Page 1: Cover Page
  addCoverPage(pdf, categoryName, subCategory.name, pageWidth, pageHeight, customTitle, customSubtitle);

  // Middle Pages: Content
  pdf.addPage();
  let yPosition = addContentPages(pdf, subCategory, margin, contentWidth, maxY);

  // If the last content page ended up being blank, remove it
  if (yPosition <= margin && pdf.getNumberOfPages() > 2) {
    pdf.deletePage(pdf.getNumberOfPages());
  }

  // Last Page: Advertisement
  pdf.addPage();
  addAdvertisementPage(pdf, pageWidth, pageHeight);

  // Download the PDF
  pdf.save(`${categoryName}-${subCategory.name}-Cheatsheet.pdf`);
}

function addCoverPage(
  pdf: jsPDF,
  categoryName: string,
  subCategoryName: string,
  pageWidth: number,
  pageHeight: number,
  customTitle?: string,
  customSubtitle?: string
) {
  pdf.setFillColor(37, 99, 235);
  pdf.rect(0, 0, pageWidth, pageHeight, 'F');
  pdf.setFillColor(59, 130, 246);
  pdf.rect(0, 0, pageWidth, pageHeight / 2, 'F');
  pdf.setFillColor(96, 165, 250);
  pdf.circle(30, 30, 40, 'F');
  pdf.circle(pageWidth - 30, pageHeight - 30, 50, 'F');

  const centerY = pageHeight / 2;
  pdf.setTextColor(255, 255, 255);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(64);
  pdf.text('CheatJS', pageWidth / 2, centerY - 40, { align: 'center' });

  pdf.setDrawColor(255, 255, 255);
  pdf.setLineWidth(0.5);
  pdf.line(pageWidth / 2 - 30, centerY - 30, pageWidth / 2 + 30, centerY - 30);

  const title = customTitle || categoryName;
  pdf.setFontSize(32);
  pdf.text(title, pageWidth / 2, centerY + 5, { align: 'center' });

  const subtitle = customSubtitle || subCategoryName;
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(24);
  pdf.text(subtitle, pageWidth / 2, centerY + 25, { align: 'center' });

  pdf.setFont('helvetica', 'italic');
  pdf.setFontSize(14);
  pdf.setTextColor(226, 232, 240);
  pdf.text('Your Quick Reference Guide', pageWidth / 2, centerY + 45, { align: 'center' });

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(11);
  pdf.setTextColor(255, 255, 255);
  const linkText = 'Generated by https://cheatjs.vercel.app';
  pdf.textWithLink(linkText, pageWidth / 2, pageHeight - 15, {
    align: 'center',
    url: 'https://cheatjs.vercel.app',
  });
}

function addContentPages(
  pdf: jsPDF,
  subCategory: SubCategory,
  margin: number,
  contentWidth: number,
  maxY: number
): number {
  let y = margin;

  const processSnippets = (snippets: Snippet[]) => {
    for (const snippet of snippets) {
      y = addSnippetToPDF(pdf, snippet, y, margin, contentWidth, maxY);
      y += 10; // Space between snippets
    }
  };

  if (subCategory.sections) {
    for (const section of subCategory.sections) {
      const sectionHeaderHeight = 15;
      if (y + sectionHeaderHeight > maxY && y > margin) {
        pdf.addPage();
        y = margin;
      }
      pdf.setFontSize(18);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(59, 130, 246);
      pdf.text(section.heading, margin, y);
      y += 10;
      processSnippets(section.snippets);
    }
  }

  if (subCategory.snippets) {
    processSnippets(subCategory.snippets);
  }

  return y;
}

function addSnippetToPDF(
  pdf: jsPDF,
  snippet: Snippet,
  startY: number,
  margin: number,
  contentWidth: number,
  maxY: number
): number {
  let y = startY;

  const checkNewPage = (requiredHeight: number): void => {
    if (y + requiredHeight > maxY) {
      pdf.addPage();
      y = margin;
    }
  };

  // --- Title ---
  checkNewPage(10);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(0, 0, 0);
  pdf.text(snippet.title, margin, y);
  y += 8;

  // --- Description ---
  const descLineHeight = 5;
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(80, 80, 80);
  const descLines = pdf.splitTextToSize(snippet.description, contentWidth);
  for (const line of descLines) {
    checkNewPage(descLineHeight);
    pdf.text(line, margin, y);
    y += descLineHeight;
  }
  y += 4;

  // --- Code Block ---
  if (snippet.code) {
    const codeLineHeight = 4;
    const codeFontSize = 8;
    const codePadding = 2;

    pdf.setFontSize(codeFontSize);
    pdf.setFont('courier', 'normal');
    pdf.setTextColor(0, 0, 0);

    const wrappedLines = pdf.splitTextToSize(snippet.code, contentWidth - codePadding * 2);

    let codeBlockStartYOnPage = y;
    let linesOnCurrentPage: string[] = [];

    const renderCodeChunk = () => {
      if (linesOnCurrentPage.length === 0) return;
      const chunkHeight = linesOnCurrentPage.length * codeLineHeight;

      // Draw background for this chunk
      pdf.setFillColor(245, 245, 245);
      pdf.rect(margin, codeBlockStartYOnPage - 3, contentWidth, chunkHeight + 4, 'F');

      // Draw text for this chunk
      let lineY = codeBlockStartYOnPage;
      for (const line of linesOnCurrentPage) {
        pdf.text(line, margin + codePadding, lineY);
        lineY += codeLineHeight;
      }
      y = lineY;
    };

    for (const line of wrappedLines) {
      if (y + codeLineHeight > maxY) {
        // Page is full, render what we have
        renderCodeChunk();
        pdf.addPage();
        y = margin;
        codeBlockStartYOnPage = y;
        linesOnCurrentPage = [];
      }
      linesOnCurrentPage.push(line);
      y += codeLineHeight; // Temporarily increment y to check for next line
    }

    // Render any remaining lines after the loop
    y = codeBlockStartYOnPage; // Reset y before final render
    renderCodeChunk();
  }

  return y;
}


function addAdvertisementPage(
  pdf: jsPDF,
  pageWidth: number,
  pageHeight: number
) {
  pdf.setFillColor(255, 255, 255);
  pdf.rect(0, 0, pageWidth, pageHeight, 'F');

  pdf.setFillColor(59, 130, 246);
  pdf.rect(0, 0, pageWidth, 60, 'F');

  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(48);
  pdf.setFont('helvetica', 'bold');
  pdf.text('CheatJS', pageWidth / 2, 40, { align: 'center' });

  const contentStartY = 85;

  pdf.setTextColor(30, 41, 59);
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  const tagline = "The easiest to understand resource to learn DSA and Frontend development on planet earth.";
  const splitTagline = pdf.splitTextToSize(tagline, pageWidth - 60);
  pdf.text(splitTagline, pageWidth / 2, contentStartY, { align: 'center' });

  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(100, 116, 139);
  pdf.text('Master modern web development with ease', pageWidth / 2, contentStartY + 20, { align: 'center' });

  const featuresStartY = contentStartY + 45;
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(59, 130, 246);
  pdf.text('What You Get:', pageWidth / 2, featuresStartY, { align: 'center' });

  const features = [
    'React, Next.js, and Frontend Concepts',
    'Data Structures & Algorithms',
    'Interactive Code Examples',
    'Beginner to Advanced Topics',
    'Always Free & Up-to-date',
  ];

  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(51, 65, 85);

  let yPos = featuresStartY + 15;
  features.forEach((feature) => {
    pdf.setFillColor(34, 197, 94);
    pdf.circle(pageWidth / 2 - 60, yPos - 2, 2, 'F');
    pdf.text(feature, pageWidth / 2 - 52, yPos, { align: 'left' });
    yPos += 10;
  });

  const ctaY = yPos + 25;

  pdf.setFillColor(239, 246, 255);
  pdf.roundedRect(pageWidth / 2 - 70, ctaY - 10, 140, 35, 3, 3, 'F');

  pdf.setDrawColor(59, 130, 246);
  pdf.setLineWidth(0.5);
  pdf.roundedRect(pageWidth / 2 - 70, ctaY - 10, 140, 35, 3, 3, 'S');

  pdf.setFontSize(13);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(59, 130, 246);
  pdf.text('Visit us at:', pageWidth / 2, ctaY + 2, { align: 'center' });

  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text('cheatjs.vercel.app', pageWidth / 2, ctaY + 14, { align: 'center' });

  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'italic');
  pdf.setTextColor(100, 116, 139);
  pdf.text('Learn faster. Code better. Build amazing things.', pageWidth / 2, ctaY + 40, { align: 'center' });

  pdf.setFillColor(248, 250, 252);
  pdf.rect(0, pageHeight - 40, pageWidth, 40, 'F');

  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(148, 163, 184);
  pdf.text('© 2024 CheatJS. All rights reserved.', pageWidth / 2, pageHeight - 15, { align: 'center' });
}