import jsPDF from 'jspdf';
import type { SubCategory, Snippet } from '../lib/cheatsheets';

export async function generateCheatsheetPDF(
  categoryName: string,
  subCategory: SubCategory,
  customTitle?: string,
  customSubtitle?: string
) {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = 210; // A4 width in mm
  const pageHeight = 297; // A4 height in mm
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;

  // Page 1: Cover Page
  addCoverPage(
    pdf,
    categoryName,
    subCategory.name,
    pageWidth,
    pageHeight,
    customTitle,
    customSubtitle
  );

  // Middle Pages: Content
  pdf.addPage();
  await addContentPages(pdf, subCategory, margin, contentWidth, pageHeight);

  // Last Page: Advertisement
  pdf.addPage();
  addAdvertisementPage(pdf, pageWidth, pageHeight);

  // Download the PDF
  pdf.save(`${categoryName}-${subCategory.name}-Cheatsheet.pdf`);
}

function addCoverPage(
  pdf: jsPDF,
  categoryName: string,
  subCategoryName: string,
  pageWidth: number,
  pageHeight: number,
  customTitle?: string,
  customSubtitle?: string
) {
  // Background - solid blue
  pdf.setFillColor(37, 99, 235); // Darker blue
  pdf.rect(0, 0, pageWidth, pageHeight, 'F');

  // Lighter blue top section for gradient effect
  pdf.setFillColor(59, 130, 246);
  pdf.rect(0, 0, pageWidth, pageHeight / 2, 'F');

  // Decorative circles with lighter blue
  pdf.setFillColor(96, 165, 250);
  pdf.circle(30, 30, 40, 'F');
  pdf.circle(pageWidth - 30, pageHeight - 30, 50, 'F');

  // Main content area
  const centerY = pageHeight / 2;

  // CheatJS Logo/Title - Large and centered
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(64);
  pdf.setFont('helvetica', 'bold');
  pdf.text('CheatJS', pageWidth / 2, centerY - 40, { align: 'center' });

  // Decorative line under logo
  pdf.setDrawColor(255, 255, 255);
  pdf.setLineWidth(0.5);
  pdf.line(pageWidth / 2 - 30, centerY - 30, pageWidth / 2 + 30, centerY - 30);

  // Title (custom or category name)
  const title = customTitle || categoryName;
  pdf.setFontSize(32);
  pdf.setFont('helvetica', 'bold');
  pdf.text(title, pageWidth / 2, centerY + 5, { align: 'center' });

  // Subtitle (custom or subcategory name)
  const subtitle = customSubtitle || subCategoryName;
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'normal');
  pdf.text(subtitle, pageWidth / 2, centerY + 25, { align: 'center' });

  // Description
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'italic');
  pdf.setTextColor(226, 232, 240); // Light gray
  pdf.text('Your Quick Reference Guide', pageWidth / 2, centerY + 45, { align: 'center' });

  // Bottom section with clickable link
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(255, 255, 255);
  const linkText = 'Generated by https://cheatjs.vercel.app';
  const linkY = pageHeight - 15;

  // Add clickable link
  pdf.textWithLink(linkText, pageWidth / 2, linkY, {
    align: 'center',
    url: 'https://cheatjs.vercel.app'
  });
}

async function addContentPages(
  pdf: jsPDF,
  subCategory: SubCategory,
  margin: number,
  contentWidth: number,
  pageHeight: number
) {
  let yPosition = margin;
  const lineHeight = 7;
  const maxY = pageHeight - margin;

  // Helper function to check if we need a new page
  const checkNewPage = (requiredSpace: number): boolean => {
    if (yPosition + requiredSpace > maxY) {
      pdf.addPage();
      yPosition = margin;
      return true;
    }
    return false;
  };

  // Process sections if they exist
  if (subCategory.sections) {
    for (const section of subCategory.sections) {
      // Section heading
      checkNewPage(15);
      pdf.setFontSize(18);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(59, 130, 246);
      pdf.text(section.heading, margin, yPosition);
      yPosition += lineHeight + 3;

      // Process snippets in section
      for (const snippet of section.snippets) {
        yPosition = addSnippetToPDF(pdf, snippet, margin, contentWidth, yPosition, maxY, lineHeight, checkNewPage);
      }
    }
  }

  // Process direct snippets if they exist
  if (subCategory.snippets) {
    for (const snippet of subCategory.snippets) {
      yPosition = addSnippetToPDF(pdf, snippet, margin, contentWidth, yPosition, maxY, lineHeight, checkNewPage);
    }
  }
}

function addSnippetToPDF(
  pdf: jsPDF,
  snippet: Snippet,
  margin: number,
  contentWidth: number,
  startY: number,
  maxY: number,
  lineHeight: number,
  checkNewPage: (space: number) => boolean
): number {
  let yPosition = startY;

  // Check if we need a new page for the snippet
  checkNewPage(30);

  // Title
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(0, 0, 0);
  pdf.text(snippet.title, margin, yPosition);
  yPosition += lineHeight;

  // Description
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(80, 80, 80);
  const descLines = pdf.splitTextToSize(snippet.description, contentWidth);
  pdf.text(descLines, margin, yPosition);
  yPosition += descLines.length * 5 + 3;

  // Code block
  if (snippet.code) {
    checkNewPage(40);

    // Code background
    pdf.setFillColor(245, 245, 245);
    const codeHeight = Math.min(60, snippet.code.split('\n').length * 4);
    pdf.rect(margin, yPosition - 3, contentWidth, codeHeight, 'F');

    // Code text
    pdf.setFontSize(8);
    pdf.setFont('courier', 'normal');
    pdf.setTextColor(0, 0, 0);

    const codeLines = snippet.code.split('\n').slice(0, 15); // Limit lines
    let codeY = yPosition;

    for (const line of codeLines) {
      if (codeY + 4 > maxY) break;
      const truncatedLine = line.substring(0, 90); // Limit line length
      pdf.text(truncatedLine, margin + 2, codeY);
      codeY += 4;
    }

    yPosition = codeY + 5;
  }

  // Add spacing between snippets
  yPosition += 5;

  // Check if we need a new page after this snippet
  if (yPosition > maxY - 30) {
    pdf.addPage();
    yPosition = margin;
  }

  return yPosition;
}

function addAdvertisementPage(
  pdf: jsPDF,
  pageWidth: number,
  pageHeight: number
) {
  // Clean white background
  pdf.setFillColor(255, 255, 255);
  pdf.rect(0, 0, pageWidth, pageHeight, 'F');

  // Decorative top section with blue accent
  pdf.setFillColor(59, 130, 246);
  pdf.rect(0, 0, pageWidth, 60, 'F');

  // CheatJS logo in white on blue background
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(48);
  pdf.setFont('helvetica', 'bold');
  pdf.text('CheatJS', pageWidth / 2, 40, { align: 'center' });

  // Main content area
  const contentStartY = 85;

  // Tagline
  pdf.setTextColor(30, 41, 59); // Dark slate
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  const tagline = "The easiest to understand resource to Data Structures, Algorithms and Frontend development on planet earth.";
  const splitTagline = pdf.splitTextToSize(tagline, pageWidth - 60);
  pdf.text(splitTagline, pageWidth / 2, contentStartY, { align: 'center' });

  // Subtitle
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(100, 116, 139); // Slate gray
  pdf.text('Master modern web development with ease', pageWidth / 2, contentStartY + 20, { align: 'center' });

  // Features section with better formatting
  const featuresStartY = contentStartY + 45;
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(59, 130, 246);
  pdf.text('What You Get:', pageWidth / 2, featuresStartY, { align: 'center' });

  // Feature list with icons and better spacing
  const features = [
    'React, Next.js, and Frontend Concepts',
    'Data Structures & Algorithms',
    'Interactive Code Examples',
    'Beginner to Advanced Topics',
    'Always Free & Up-to-date',
  ];

  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(51, 65, 85); // Dark slate

  let yPos = featuresStartY + 15;
  features.forEach((feature) => {
    // Checkmark circle
    pdf.setFillColor(34, 197, 94); // Green
    pdf.circle(pageWidth / 2 - 60, yPos - 2, 2, 'F');

    // Feature text
    pdf.text(feature, pageWidth / 2 - 52, yPos, { align: 'left' });
    yPos += 10;
  });

  // Call to action box
  const ctaY = yPos + 25;

  // CTA background box
  pdf.setFillColor(239, 246, 255); // Light blue
  pdf.roundedRect(pageWidth / 2 - 70, ctaY - 10, 140, 35, 3, 3, 'F');

  // CTA border
  pdf.setDrawColor(59, 130, 246);
  pdf.setLineWidth(0.5);
  pdf.roundedRect(pageWidth / 2 - 70, ctaY - 10, 140, 35, 3, 3, 'S');

  // CTA text
  pdf.setFontSize(13);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(59, 130, 246);
  pdf.text('Visit us at:', pageWidth / 2, ctaY + 2, { align: 'center' });

  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text('cheatjs.vercel.app', pageWidth / 2, ctaY + 14, { align: 'center' });

  // Bottom tagline
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'italic');
  pdf.setTextColor(100, 116, 139);
  pdf.text('Learn faster. Code better. Build amazing things.', pageWidth / 2, ctaY + 40, { align: 'center' });

  // Decorative bottom section
  pdf.setFillColor(248, 250, 252);
  pdf.rect(0, pageHeight - 40, pageWidth, 40, 'F');

  // Footer
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(148, 163, 184);
  pdf.text('© 2025 CheatJS. All rights reserved.', pageWidth / 2, pageHeight - 15, { align: 'center' });
}