import jsPDF from 'jspdf';
import type { SubCategory, Snippet } from '../lib/cheatsheets';

export async function generateCheatsheetPDF(
  categoryName: string,
  subCategory: SubCategory,
  customTitle?: string,
  customSubtitle?: string
) {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = 210; // A4 width in mm
  const pageHeight = 297; // A4 height in mm
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;

  // Page 1: Cover Page
  addCoverPage(
    pdf,
    categoryName,
    subCategory.name,
    pageWidth,
    pageHeight,
    customTitle,
    customSubtitle
  );

  // Middle Pages: Content
  pdf.addPage();
  const lastYPosition = addContentPages(pdf, subCategory, margin, contentWidth, pageHeight);

  // If the last content page ended up being blank, remove it.
  if (lastYPosition <= margin) {
    pdf.deletePage(pdf.getNumberOfPages());
  }

  // Last Page: Advertisement
  pdf.addPage();
  addAdvertisementPage(pdf, pageWidth, pageHeight);

  // Download the PDF
  pdf.save(`${categoryName}-${subCategory.name}-Cheatsheet.pdf`);
}

function addCoverPage(
  pdf: jsPDF,
  categoryName: string,
  subCategoryName: string,
  pageWidth: number,
  pageHeight: number,
  customTitle?: string,
  customSubtitle?: string
) {
  // Background - solid blue
  pdf.setFillColor(37, 99, 235);
  pdf.rect(0, 0, pageWidth, pageHeight, 'F');

  // Lighter blue top section for gradient effect
  pdf.setFillColor(59, 130, 246);
  pdf.rect(0, 0, pageWidth, pageHeight / 2, 'F');

  // Decorative circles with lighter blue
  pdf.setFillColor(96, 165, 250);
  pdf.circle(30, 30, 40, 'F');
  pdf.circle(pageWidth - 30, pageHeight - 30, 50, 'F');

  const centerY = pageHeight / 2;

  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(64);
  pdf.setFont('helvetica', 'bold');
  pdf.text('CheatJS', pageWidth / 2, centerY - 40, { align: 'center' });

  pdf.setDrawColor(255, 255, 255);
  pdf.setLineWidth(0.5);
  pdf.line(pageWidth / 2 - 30, centerY - 30, pageWidth / 2 + 30, centerY - 30);

  const title = customTitle || categoryName;
  pdf.setFontSize(32);
  pdf.setFont('helvetica', 'bold');
  pdf.text(title, pageWidth / 2, centerY + 5, { align: 'center' });

  const subtitle = customSubtitle || subCategoryName;
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'normal');
  pdf.text(subtitle, pageWidth / 2, centerY + 25, { align: 'center' });

  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'italic');
  pdf.setTextColor(226, 232, 240);
  pdf.text('Your Quick Reference Guide', pageWidth / 2, centerY + 45, { align: 'center' });

  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(255, 255, 255);
  const linkText = 'Generated by https://cheatjs.vercel.app';
  const linkY = pageHeight - 15;

  pdf.textWithLink(linkText, pageWidth / 2, linkY, {
    align: 'center',
    url: 'https://cheatjs.vercel.app'
  });
}

function addContentPages(
  pdf: jsPDF,
  subCategory: SubCategory,
  margin: number,
  contentWidth: number,
  pageHeight: number
) {
  let yPosition = margin;
  const maxY = pageHeight - margin;

  const processSnippets = (snippets: Snippet[]) => {
    for (const snippet of snippets) {
      yPosition = addSnippetToPDF(pdf, snippet, margin, contentWidth, yPosition, maxY);
      yPosition += 10; // Spacing between snippets
    }
  };

  if (subCategory.sections) {
    for (const section of subCategory.sections) {
      const sectionHeaderHeight = 15;
      if (yPosition + sectionHeaderHeight > maxY) {
        pdf.addPage();
        yPosition = margin;
      }
      pdf.setFontSize(18);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(59, 130, 246);
      pdf.text(section.heading, margin, yPosition);
      yPosition += 10;

      processSnippets(section.snippets);
    }
  }

  if (subCategory.snippets) {
    processSnippets(subCategory.snippets);
  }

  return yPosition;
}

// ===================================================================
// ===== VVVV THIS IS THE FULLY REVISED AND CORRECTED FUNCTION VVVV
// ===================================================================

function addSnippetToPDF(
  pdf: jsPDF,
  snippet: Snippet,
  margin: number,
  contentWidth: number,
  startY: number,
  maxY: number
): number {
  let yPosition = startY;

  // Helper to add a new page if content doesn't fit
  const checkAndAddPage = (requiredHeight: number) => {
    if (yPosition + requiredHeight > maxY) {
      pdf.addPage();
      yPosition = margin;
    }
  };

  // --- Title ---
  checkAndAddPage(10);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(0, 0, 0);
  pdf.text(snippet.title, margin, yPosition);
  yPosition += 8;

  // --- Description ---
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(80, 80, 80);
  const descLines = pdf.splitTextToSize(snippet.description, contentWidth);

  for (const line of descLines) {
    checkAndAddPage(5);
    pdf.text(line, margin, yPosition);
    yPosition += 5;
  }
  yPosition += 3;

  // --- Code Block ---
  if (snippet.code) {
    const codeLineHeight = 4;
    const codeFontSize = 8;
    const codePadding = 2;

    pdf.setFontSize(codeFontSize);
    pdf.setFont('courier', 'normal');
    pdf.setTextColor(0, 0, 0);

    const allLines = snippet.code.split('\n');
    const wrappedLines: string[] = [];
    allLines.forEach(line => {
      wrappedLines.push(...pdf.splitTextToSize(line, contentWidth - codePadding * 2));
    });

    let lineBuffer: string[] = [];

    const drawBuffer = () => {
      if (lineBuffer.length === 0) return;

      const bufferHeight = lineBuffer.length * codeLineHeight;
      checkAndAddPage(bufferHeight + 5);

      // 1. DRAW BACKGROUND FIRST
      pdf.setFillColor(245, 245, 245);
      pdf.rect(margin, yPosition - 2, contentWidth, bufferHeight + 4, 'F');

      // 2. DRAW TEXT ON TOP
      for (const line of lineBuffer) {
        pdf.text(line, margin + codePadding, yPosition);
        yPosition += codeLineHeight;
      }
      lineBuffer = []; // Clear buffer
    };

    for (const line of wrappedLines) {
      const requiredHeight = (lineBuffer.length + 1) * codeLineHeight;
      if (yPosition + requiredHeight > maxY) {
        drawBuffer();
      }
      lineBuffer.push(line);
    }

    // Draw any remaining lines in the buffer
    drawBuffer();
  }

  return yPosition;
}

// ===================================================================
// ===== ^^^^ THIS IS THE FULLY REVISED AND CORRECTED FUNCTION ^^^^
// ===================================================================

function addAdvertisementPage(
  pdf: jsPDF,
  pageWidth: number,
  pageHeight: number
) {
  pdf.setFillColor(255, 255, 255);
  pdf.rect(0, 0, pageWidth, pageHeight, 'F');

  pdf.setFillColor(59, 130, 246);
  pdf.rect(0, 0, pageWidth, 60, 'F');

  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(48);
  pdf.setFont('helvetica', 'bold');
  pdf.text('CheatJS', pageWidth / 2, 40, { align: 'center' });

  const contentStartY = 85;

  pdf.setTextColor(30, 41, 59);
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  const tagline = "The easiest to understand resource to learn DSA and Frontend development on planet earth.";
  const splitTagline = pdf.splitTextToSize(tagline, pageWidth - 60);
  pdf.text(splitTagline, pageWidth / 2, contentStartY, { align: 'center' });

  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(100, 116, 139);
  pdf.text('Master modern web development with ease', pageWidth / 2, contentStartY + 20, { align: 'center' });

  const featuresStartY = contentStartY + 45;
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(59, 130, 246);
  pdf.text('What You Get:', pageWidth / 2, featuresStartY, { align: 'center' });

  const features = [
    'React, Next.js, and Frontend Concepts',
    'Data Structures & Algorithms',
    'Interactive Code Examples',
    'Beginner to Advanced Topics',
    'Always Free & Up-to-date',
  ];

  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(51, 65, 85);

  let yPos = featuresStartY + 15;
  features.forEach((feature) => {
    pdf.setFillColor(34, 197, 94);
    pdf.circle(pageWidth / 2 - 60, yPos - 2, 2, 'F');
    pdf.text(feature, pageWidth / 2 - 52, yPos, { align: 'left' });
    yPos += 10;
  });

  const ctaY = yPos + 25;

  pdf.setFillColor(239, 246, 255);
  pdf.roundedRect(pageWidth / 2 - 70, ctaY - 10, 140, 35, 3, 3, 'F');

  pdf.setDrawColor(59, 130, 246);
  pdf.setLineWidth(0.5);
  pdf.roundedRect(pageWidth / 2 - 70, ctaY - 10, 140, 35, 3, 3, 'S');

  pdf.setFontSize(13);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(59, 130, 246);
  pdf.text('Visit us at:', pageWidth / 2, ctaY + 2, { align: 'center' });

  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text('cheatjs.vercel.app', pageWidth / 2, ctaY + 14, { align: 'center' });

  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'italic');
  pdf.setTextColor(100, 116, 139);
  pdf.text('Learn faster. Code better. Build amazing things.', pageWidth / 2, ctaY + 40, { align: 'center' });

  pdf.setFillColor(248, 250, 252);
  pdf.rect(0, pageHeight - 40, pageWidth, 40, 'F');

  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(148, 163, 184);
  pdf.text('© 2024 CheatJS. All rights reserved.', pageWidth / 2, pageHeight - 15, { align: 'center' });
}